services:
    frontendsearch.boost.fulltext:
        class: Phlexible\FrontendSearchBundle\Boost\FulltextBoost

    frontendsearch.query.fulltext:
        class: Phlexible\FrontendSearchBundle\Query\FulltextQuery
        arguments: ["@indexer.query.parser", "@frontendsearch.boost.fulltext"]
        tags:
            - {name: "indexer.search"}

    frontendsearch.search:
        class: Phlexible\FrontendSearchBundle\Search\Search
        arguments:
            - @frontendsearch.cache
            - @event_dispatcher
            - @indexer.search
            - @frontendsearch.query.fulltext
            - @elements.repository
            - @elements.context.manager
            - @tree.manager

    frontendsearch.boost.suggest:
        class: Phlexible\FrontendSearchBundle\Boost\SuggestBoost

    frontendsearch.query.suggest:
        class: Phlexible\FrontendSearchBundle\Query\SuggestQuery
        arguments: [@indexer.query.parser, @frontendsearch.boost.suggest]
        tags:
            -  {name: "indexer.search"}

    # event listeners
    frontendsearch.listener.search:
        class: Phlexible\FrontendSearchBundle\EventListener\SearchListener
        tags:
            - {name: "kernel.event_listener", event: suche, method: onSearch}
