services:
    phlexible_frontend_search.suggest:
        class: Makeweb_FrontendSolrSuggest_Suggest
        arguments: [@phlexible_frontend_search.cache, @indexerstoragesolr.driver, @phlexible_frontend_search.configuration]

    phlexible_frontend_search.configuration:
        class: Makeweb_FrontendSolrSuggest_Configuration
        arguments:
            -
                use_context: %phlexible_frontend_search.use_context%
                query.field_config: %phlexible_frontend_search.query.field_config%
                query.min_token_length: %phlexible_frontend_search.query.min_token_length%
                query.skip_restricted: %phlexible_frontend_search.query.skip_restricted%
                levenshtein.cost_insert: %phlexible_frontend_search.levenshtein.cost.insert%
                levenshtein.cost_replace: %phlexible_frontend_search.levenshtein.cost.replace%
                levenshtein.cost_delete: %phlexible_frontend_search.levenshtein.cost.delete%
                levenshtein.max: %phlexible_frontend_search.levenshtein.max%
                solr.partial_enable: %phlexible_frontend_search.solr.partial.enable%
                solr.partial_boost: %phlexible_frontend_search.solr.partial.boost%
                solr.fuzzy_enable: %phlexible_frontend_search.solr.fuzzy.enable%
                solr.fuzzy_boost: %phlexible_frontend_search.solr.fuzzy.boost%
                solr.fuzzy_sim: %phlexible_frontend_search.solr.fuzzy.sim%
                solr.fuzzy_min_length: %phlexible_frontend_search.solr.fuzzy.min_length%
                solr.subquery_size: %phlexible_frontend_search.solr.subquery.size%
                solr.subquery_size_restricted: %phlexible_frontend_search.solr.subquery.size_restricted%
                result.suggestions: %phlexible_frontend_search.result.suggestions%

    phlexible_frontend_search.mapper:
        class: Makeweb_FrontendSolrSuggest_Mapper
        arguments: [@phlexible_frontend_search.configuration]

    # event listeners
    phlexible_frontend_search.listener.document:
        class: Phlexible\FrontendSearchSuggestBundle\EventListener\DocumentListener
        tags:
            - {name: kernel.event_listener, event: phlexible_indexer.create_document, method: onCreateDocument}
            - {name: kernel.event_listener, event: phlexible_indexerelement.map_document, method: onIndexerElementsMapDocument}
            - {name: kernel.event_listener, event: phlexible_indexerelementmedia.map_document, method: onIndexerElementsMediaMapDocument}
