services:
    frontendsearch.boost.fulltext:
        class: Phlexible\FrontendSearchComponent\Boost\FulltextBoost

    frontendsearch.query.fulltext:
        class: Phlexible\FrontendSearchComponent\Query\FulltextQuery
        arguments: ["@indexer.query.parser", "@frontendsearch.boost.fulltext"]
        tags:
            - {name: "indexer.search"}

    frontendsearch.search:
        class: Phlexible\FrontendSearchComponent\Search\Search
        arguments:
            - @frontendsearch.cache
            - @dispatcher
            - @indexer.search
            - @frontendsearch.query.fulltext
            - @elements.repository
            - @elements.context.manager
            - @tree.manager

    frontendsearch.boost.suggest:
        class: Phlexible\FrontendSearchComponent\Boost\SuggestBoost

    frontendsearch.query.suggest:
        class: Phlexible\FrontendSearchComponent\Query\SuggestQuery
        arguments: [@indexer.query.parser, @frontendsearch.boost.suggest]
        tags:
            -  {name: "indexer.search"}

    # listeners
    frontendsearch.listener.search:
        class: Phlexible\FrontendSearchComponent\Listener\SearchListener
        tags:
            - {name: "event.listener", event: suche, method: onSearch}
